# Generated by Django 4.0.6 on 2022-07-29 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Numberplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplayed', models.IntegerField(max_length=50)),
                ('mega', models.CharField(choices=[('Gold', 'Mega'), ('White', 'No Mega')], max_length=50)),
                ('sale_date', models.DateTimeField(auto_now=True)),
                ('draw', models.CharField(choices=[('8:30', 'Early Bird'), ('10:30', 'Drive Time'), ('1:00', 'Midday'), ('3:00', 'Afternoon'), ('5:00', 'Evening'), ('8:25', 'Late Night')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sell', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('draw_time', models.CharField(choices=[('8:30', 'Early Bird'), ('10:30', 'Drive Time'), ('1:00', 'Midday'), ('3:00', 'Afternoon'), ('5:00', 'Evening'), ('8:25', 'Late Night')], max_length=50)),
                ('draw_date', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
