# Generated by Django 4.0.6 on 2022-08-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspotapp', '0002_alter_numberplay_numberplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='ticket_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='numberplay',
            name='sale_date',
            field=models.DateTimeField(verbose_name='sale date'),
        ),
    ]
