# Generated by Django 4.0.6 on 2022-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspotapp', '0003_ticketsale_ticket_number_alter_numberplay_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='ticket_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
