# Generated by Django 4.0.6 on 2022-08-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspotapp', '0008_alter_numberplay_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='draw_date',
            field=models.DateField(auto_now=True),
        ),
    ]
