# Generated by Django 4.0.6 on 2022-08-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspotapp', '0009_alter_ticketsale_draw_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
