# Generated by Django 4.0.6 on 2022-08-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caspotapp', '0010_ticketsale_win'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsale',
            old_name='win',
            new_name='won',
        ),
    ]
