# Generated by Django 4.0.6 on 2022-08-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspotapp', '0011_rename_win_ticketsale_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplay',
            name='draw',
            field=models.CharField(choices=[('Early Bird', 'Early Bird'), ('Drive Time', 'Drive Time'), ('Midday', 'Midday'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Late Night', 'Late Night')], max_length=50),
        ),
    ]
