# Generated by Django 4.0.6 on 2022-08-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspotapp', '0013_alter_ticketsale_draw_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplay',
            name='draw',
            field=models.CharField(choices=[('1', 'Early Bird'), ('2', 'Drive Time'), ('3', 'Midday'), ('4', 'Afternoon'), ('5', 'Evening'), ('6', 'Late Night')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='draw_time',
            field=models.CharField(choices=[('1', 'Early Bird'), ('2', 'Drive Time'), ('3', 'Midday'), ('4', 'Afternoon'), ('5', 'Evening'), ('6', 'Late Night')], max_length=50),
        ),
    ]
