# Generated by Django 4.0.6 on 2022-08-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspotapp', '0015_alter_numberplay_draw_alter_ticketsale_draw_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='draw_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='draw_time',
            field=models.CharField(choices=[('8:30', 'Early Bird'), ('10:30', 'Morning'), ('1:00', 'Midday'), ('3:00', 'Afternoon'), ('5:00', 'Drivetime'), ('8:25', 'Evening')], max_length=50),
        ),
    ]
